### ISSUE TITLE
C-v key binding should not be bound when cua-mode key bindings are disabled

### ISSUE THREAD

**Issue by tuhdo** [sabof/auto-auto-indent#2]
Some people may not use cua-mode with its key bindings but 
rectangular features (like myself). C-v is bound with a yank
command even if cua-mode key bindings are not enabled. This 
change fixes this issue.

This line:

 (when cua-mode....

Should be replaced with:

  (when (and cua-mode cua-enable-cua-keys) ....

**Comment by sabof** [comment]
Try the latest commit

**Comment by tuhdo** [comment]
It is fixed. Thanks.
